import { describe, expect, it, vi, afterEach } from 'vitest'
import type { ReactElement } from 'react'
import { render, screen, waitFor } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { Inventory } from './Inventory'

const renderWithClient = (ui: ReactElement, queryClient: QueryClient) =>
  render(<QueryClientProvider client={queryClient}>{ui}</QueryClientProvider>)

describe('Inventory page', () => {
  afterEach(() => {
    vi.restoreAllMocks()
  })

  it('renders inventory snapshot from API', async () => {
    const mockPayload = {
      manifest: { version: '2025-10-26', maintainer: 'Security & Platform', reviewCadence: 'quarterly' },
      summary: { total: 3, byType: { filesystem: 2, secret: 1 }, byClassification: { confidential: 2, sensitive: 1 } },
      requirements: [
        { id: 'backend-service', surface: 'backend', description: 'Inventory manifest loader, validator, and cache', status: 'implemented', detail: null },
      ],
      assets: [
        {
          id: 'refined-exports',
          name: 'Refined single source of truth exports',
          type: 'filesystem',
          classification: 'confidential',
          owner: 'Product',
          custodian: 'Platform Engineering',
          location: './dist',
          description: 'Excel workbooks generated by the pipeline.',
          dependencies: ['Pipeline formatting module'],
          controls: ['Access logging required per SOC2-005'],
        },
      ],
      generatedAt: '2025-11-01T00:00:00Z',
    }

    const fetchMock = vi.fn(() =>
      Promise.resolve({
        ok: true,
        statusText: 'OK',
        json: () => Promise.resolve(mockPayload),
      }),
    ) as unknown as typeof fetch

    vi.stubGlobal('fetch', fetchMock)

    const queryClient = new QueryClient({
      defaultOptions: {
        queries: {
          retry: false,
        },
      },
    })

    renderWithClient(<Inventory />, queryClient)

    await waitFor(() => expect(screen.getByText('Asset inventory')).toBeInTheDocument())
    expect(screen.getByText('Refined single source of truth exports')).toBeInTheDocument()
    queryClient.clear()
  })
})
